# Configuration file for Calamares - AetherOS System Installer
# Syntax is YAML 1.2
---
modules-search: [ local, /usr/lib/calamares/modules, /usr/lib64/calamares/modules ]

instances:
  - id:       root
    module:   unpackfs
    config:   unpackfs.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs@root
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - displaymanager
      - grubcfg
      - initramfs
      - packages
      - umount
  - show:
      - finished

branding: aetheros

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
