# Bootloader module configuration for AetherOS (Dual-Boot & UEFI/BIOS support)
---
efiBootLoader: "grub"

kernel: "/boot/vmlinuz"
img: "/boot/initramfs.img"
fallback: "/boot/initramfs-fallback.img"
timeout: "5"

bootloaderCommandLine: "rhgb quiet splash loglevel=3 vga=current"

grubInstall: "grub2-install"
grubMkconfig: "grub2-mkconfig"
grubCfg: "/boot/grub2/grub.cfg"
grubProbe: "grub2-probe"
efiBootMgr: "efibootmgr"

installEpel: false
