# Display Manager configuration for AetherOS (SDDM)
---
displaymanagers:
  - sddm

defaultDesktopEnvironment:
    executable: "Hyprland"
    desktopFile: "hyprland"

basicSetup: true
sysconfigSetup: false
