# Partitioning configuration for AetherOS (Btrfs / Ext4 support)
---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: none
defaultFileSystemType: "btrfs"
availableFileSystemTypes: ["btrfs", "ext4", "xfs"]

btrfsSubvolumes:
    - mountPoint: /
      subvolume: /@
    - mountPoint: /home
      subvolume: /@home
    - mountPoint: /var
      subvolume: /@var
    - mountPoint: /var/log
      subvolume: /@log
    - mountPoint: /var/cache
      subvolume: /@cache
