# User configuration module for AetherOS Installer
---
defaultGroups:
    - wheel
    - audio
    - video
    - input
    - dialout
    - storage
    - optical
    - network
    - systemd-journal

autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
doReusePassword: true
passwordRequirements:
    nonempty: true
