# Welcome module configuration for AetherOS Installer
---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
    requiredStorage:    15.0
    requiredRam:        2.0
    internetCheckUrl:   https://fedoraproject.org
    check:
        - storage
        - ram
        - power
        - root
    required:
        - storage
        - ram
        - root

geoip:
    style: "none"
