# AetherOS Master SDDM Configuration
[General]
DisplayServer=wayland
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=aetheros-glass
ThemeDir=/usr/share/sddm/themes

[Users]
MaximumUid=60000
MinimumUid=1000
RememberLastUser=true
RememberLastSession=true

[Wayland]
SessionDir=/usr/share/wayland-sessions
