# ~/.config/wal/templates/colors-hyprland.conf
$background = rgb({background.strip})
$foreground = rgb({foreground.strip})
$accent1 = rgb({color1.strip})
$accent2 = rgb({color2.strip})
$accent3 = rgb({color3.strip})
