# GDM configuration for AetherOS Live & Installed Environment
[daemon]
WaylandEnable=true
AutomaticLoginEnable=True
AutomaticLogin=liveuser
DefaultSession=gnome.desktop

[security]

[xdmcp]

[chooser]

[debug]
