[General]
DisplayServer=wayland
GreeterEnvironment=QML_ENABLE_DISK_CACHE=1

[Wayland]
# Use minimal Hyprland instance as the greeter compositor
CompositorCommand=Hyprland --config /etc/sddm.conf.d/hyprland-sddm.conf
