preload = /usr/share/backgrounds/aetheros/sunset_mountains.png
preload = /usr/share/backgrounds/aetheros/autumn_forest.png
wallpaper = ,/usr/share/backgrounds/aetheros/sunset_mountains.png
splash = false
ipc = on
