# /etc/calamares/modules/shellprocess.conf
# AetherOS Calamares Shellprocess - Provisions OOBE on Target Disk
---
i18n:
    name: "Preparing Aether OS Welcome Wizard..."
dontChroot: false
timeout: 60
script:
    - command: "/bin/bash /etc/calamares/scripts/setup-oobe.sh"
